// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appHealth: () => __TAURI_INVOKE<AppHealth>("app_health"),
	libraryChooseRoot: () => typedError<{
	libraryId: string,
	rootInstanceHash: string,
	rootPath: string,
	trackCount: number,
	status: LibraryStatus,
} | null, string>(__TAURI_INVOKE("library_choose_root")),
	libraryStatus: () => typedError<{
	libraryId: string,
	rootInstanceHash: string,
	rootPath: string,
	trackCount: number,
	status: LibraryStatus,
} | null, string>(__TAURI_INVOKE("library_status")),
	artworkThumbnail: (artworkKey: string, dimension: number) => typedError<string | null, string>(__TAURI_INVOKE("artwork_thumbnail", { artworkKey, dimension })),
	lyricsResolve: (trackId: string, allowNetwork: boolean) => typedError<LyricsResolution, string>(__TAURI_INVOKE("lyrics_resolve", { trackId, allowNetwork })),
	lyricsChooseCandidate: (trackId: string, candidateId: number) => typedError<LyricsResolution, string>(__TAURI_INVOKE("lyrics_choose_candidate", { trackId, candidateId })),
	queryParse: (input: string) => typedError<Expr, string>(__TAURI_INVOKE("query_parse", { input })),
	queryExecute: (request: QueryRequest) => typedError<QueryPage, string>(__TAURI_INVOKE("query_execute", { request })),
	searchGlobal: (request: SearchRequest) => typedError<GlobalSearchResults, string>(__TAURI_INVOKE("search_global", { request })),
	viewsList: () => typedError<ViewDefinition[], string>(__TAURI_INVOKE("views_list")),
	viewsSave: (view: ViewDefinition) => typedError<ViewDefinition, string>(__TAURI_INVOKE("views_save", { view })),
	viewsDuplicate: (sourceId: string, name: string) => typedError<ViewDefinition, string>(__TAURI_INVOKE("views_duplicate", { sourceId, name })),
	viewsDelete: (id: string) => typedError<null, string>(__TAURI_INVOKE("views_delete", { id })),
	viewsSetPinned: (ids: string[]) => typedError<string[], string>(__TAURI_INVOKE("views_set_pinned", { ids })),
	albumDetail: (albumKey: string) => typedError<{
	album: AlbumDto,
	tracks: TrackDto[],
} | null, string>(__TAURI_INVOKE("album_detail", { albumKey })),
	artistDetail: (artistKey: string) => typedError<{
	artist: ArtistDto,
	albums: AlbumDto[],
	tracks: TrackDto[],
} | null, string>(__TAURI_INVOKE("artist_detail", { artistKey })),
	playerPlayCollection: (trackIds: string[], startTrackId: string, mode: QueueInsertMode) => typedError<PlayerSnapshot, string>(__TAURI_INVOKE("player_play_collection", { trackIds, startTrackId, mode })),
	playerGetState: () => typedError<PlayerSnapshot, string>(__TAURI_INVOKE("player_get_state")),
	playerPause: () => typedError<PlayerSnapshot, string>(__TAURI_INVOKE("player_pause")),
	playerResume: () => typedError<PlayerSnapshot, string>(__TAURI_INVOKE("player_resume")),
	playerSeek: (positionMs: number | null) => typedError<PlayerSnapshot, string>(__TAURI_INVOKE("player_seek", { positionMs })),
	playerNext: () => typedError<PlayerSnapshot, string>(__TAURI_INVOKE("player_next")),
	playerPrevious: () => typedError<PlayerSnapshot, string>(__TAURI_INVOKE("player_previous")),
	playerSetVolume: (volume: number) => typedError<PlayerSnapshot, string>(__TAURI_INVOKE("player_set_volume", { volume })),
	playerSetShuffle: (enabled: boolean) => typedError<PlayerSnapshot, string>(__TAURI_INVOKE("player_set_shuffle", { enabled })),
	playerSetRepeat: (repeat: RepeatMode) => typedError<PlayerSnapshot, string>(__TAURI_INVOKE("player_set_repeat", { repeat })),
	playlistsList: () => typedError<PlaylistCatalog, string>(__TAURI_INVOKE("playlists_list")),
	playlistsCreate: (draft: PlaylistDraft) => typedError<Playlist, string>(__TAURI_INVOKE("playlists_create", { draft })),
	playlistsUpdate: (playlist: Playlist) => typedError<Playlist, string>(__TAURI_INVOKE("playlists_update", { playlist })),
	playlistsDelete: (id: string) => typedError<null, string>(__TAURI_INVOKE("playlists_delete", { id })),
	playlistsResolve: (id: string) => typedError<ResolvedPlaylist, string>(__TAURI_INVOKE("playlists_resolve", { id })),
	favoriteSet: (trackId: string, value: boolean) => typedError<HistoryEvent, string>(__TAURI_INVOKE("favorite_set", { trackId, value })),
	themesList: () => typedError<ThemeCatalog, string>(__TAURI_INVOKE("themes_list")),
	themeGetEditable: (id: string) => typedError<EditableTheme, string>(__TAURI_INVOKE("theme_get_editable", { id })),
	themeResolve: (id: string, artworkKey: string | null) => typedError<ResolvedTheme, string>(__TAURI_INVOKE("theme_resolve", { id, artworkKey })),
	themeDuplicate: (sourceId: string, name: string) => typedError<ThemeSummary, string>(__TAURI_INVOKE("theme_duplicate", { sourceId, name })),
	themeSaveEdits: (id: string, name: string, tokens: { [key in string]: ThemeTokenValue }) => typedError<ThemeSummary, string>(__TAURI_INVOKE("theme_save_edits", { id, name, tokens })),
	themeImport: (json: string, replace: boolean) => typedError<ThemeSummary, string>(__TAURI_INVOKE("theme_import", { json, replace })),
	themeExport: (id: string) => typedError<string, string>(__TAURI_INVOKE("theme_export", { id })),
	themeDelete: (id: string) => typedError<ThemeSelectionDto, string>(__TAURI_INVOKE("theme_delete", { id })),
	themeSelection: () => typedError<ThemeSelectionDto, string>(__TAURI_INVOKE("theme_selection")),
	themeSetSelection: (appearance: ThemeAppearance, id: string, followSystemAppearance: boolean) => typedError<ThemeSelectionDto, string>(__TAURI_INVOKE("theme_set_selection", { appearance, id, followSystemAppearance })),
	themeTokenRegistry: () => __TAURI_INVOKE<ThemeTokenDescriptor[]>("theme_token_registry"),
};

/** Events */
export const events = {
	libraryScanProgress: makeEvent<LibraryScanEvent>("library://scan-progress"),
	playerError: makeEvent<PlayerErrorEvent>("player://error"),
	playerQueueChanged: makeEvent<PlayerQueueChangedEvent>("player://queue-changed"),
	playerState: makeEvent<PlayerStateEvent>("player://state"),
	playerTrackChanged: makeEvent<PlayerTrackChangedEvent>("player://track-changed"),
};

/* Types */
export type AlbumDetailDto = {
	album: AlbumDto,
	tracks: TrackDto[],
};

export type AlbumDto = {
	albumKey: string,
	title: string,
	albumArtist: string,
	year: number | null,
	trackCount: number,
	durationMs: number | null,
	artworkKey: string | null,
	unknown: boolean,
};

export type AppHealth = {
	appName: string,
	version: string,
	status: string,
};

export type ArtistDetailDto = {
	artist: ArtistDto,
	albums: AlbumDto[],
	tracks: TrackDto[],
};

export type ArtistDto = {
	artistKey: string,
	name: string,
	albumCount: number,
	trackCount: number,
};

export type EditableTheme = {
	id: string,
	name: string,
	appearance: ThemeAppearance,
	basedOn: string | null,
	builtIn: boolean,
	tokens: { [key in string]: ThemeTokenValue },
};

export type EntityKind = "track" | "album" | "artist" | "folder" | "genre";

export type EventTrack = {
	path: string,
	hint: TrackHint,
};

export type Expr = { kind: "and"; items: Expr[] } | { kind: "or"; items: Expr[] } | { kind: "not"; item: Expr } | { kind: "text"; value: string } | { kind: "predicate"; field: QueryField; op: QueryOperator; value: QueryValue };

export type FolderDto = {
	path: string,
	name: string,
	trackCount: number,
};

export type GenreDto = {
	name: string,
	trackCount: number,
};

export type GlobalSearchResults = {
	query: Expr,
	artists: ArtistDto[],
	albums: AlbumDto[],
	tracks: TrackDto[],
	folders: FolderDto[],
	genres: GenreDto[],
	playlists: NamedSearchResult[],
	views: NamedSearchResult[],
};

export type HistoryEvent = {
	id: string,
	ts: string,
	type: HistoryEventType,
	track: EventTrack,
	payload: HistoryPayload,
};

export type HistoryEventType = "played" | "skipped" | "favorite_set";

export type HistoryPayload = ({ seconds: number | null }) & { value?: never } | ({ value: boolean }) & { seconds?: never };

export type LayoutKind = "grid" | "list" | "table";

export type LibraryScanEvent = {
	summary: LibrarySummary,
	progress: ScanProgress,
	error: string | null,
};

export type LibraryStatus = "ready" | "scanning" | "failed";

export type LibrarySummary = {
	libraryId: string,
	rootInstanceHash: string,
	rootPath: string,
	trackCount: number,
	status: LibraryStatus,
};

export type LyricsCandidate = {
	id: number,
	trackName: string,
	artistName: string,
	albumName: string,
	durationSeconds: number | null,
	hasSyncedLyrics: boolean,
	confidence: LyricsMatchConfidence,
	durationDeltaMs: number | null,
	reasons: string[],
};

export type LyricsDocument = {
	source: LyricsSource,
	synced: boolean,
	instrumental: boolean,
	lines: LyricsLine[],
	plainText: string | null,
};

export type LyricsLine = {
	timestampMs: number,
	text: string,
};

export type LyricsMatchConfidence = "high" | "review";

export type LyricsResolution = {
	document: LyricsDocument | null,
	candidates: LyricsCandidate[],
	message: string | null,
};

export type LyricsSource = "sidecar" | "embedded" | "portable" | "lrclib";

export type NamedSearchResult = {
	id: string,
	name: string,
	kind: string,
};

export type PlaybackStatus = "idle" | "loading" | "playing" | "paused" | "error";

export type PlayerErrorEvent = {
	message: string,
	recoverable: boolean,
};

export type PlayerQueueChangedEvent = {
	queue: PlayerQueueItem[],
	playOrder: string[],
	currentIndex: number | null,
};

export type PlayerQueueItem = {
	queueId: string,
	track: TrackDto,
};

export type PlayerSnapshot = {
	status: PlaybackStatus,
	queue: PlayerQueueItem[],
	playOrder: string[],
	currentIndex: number | null,
	currentTrack: PlayerQueueItem | null,
	positionMs: number | null,
	durationMs: number | null,
	volume: number,
	shuffle: boolean,
	repeat: RepeatMode,
	error: string | null,
	outputDevice: string | null,
};

export type PlayerStateEvent = {
	status: PlaybackStatus,
	positionMs: number | null,
	durationMs: number | null,
	volume: number,
	shuffle: boolean,
	repeat: RepeatMode,
	error: string | null,
	outputDevice: string | null,
};

export type PlayerTrackChangedEvent = {
	currentTrack: PlayerQueueItem | null,
};

export type Playlist = { type: "static"; schema_version: number; id: string; name: string; items: StaticPlaylistItem[] } | { type: "smart"; schema_version: number; id: string; name: string; query: Expr; sort: QuerySort[] };

export type PlaylistCatalog = {
	playlists: Playlist[],
	warnings: string[],
};

export type PlaylistDraft = { type: "static"; name: string; items: StaticPlaylistItem[] } | { type: "smart"; name: string; query: Expr; sort: QuerySort[] };

export type QueryField = "title" | "artist" | "albumArtist" | "album" | "genre" | "composer" | "year" | "track" | "disc" | "duration" | "codec" | "sampleRate" | "bitDepth" | "channels" | "bitrate" | "path" | "addedAt" | "lastPlayed" | "playCount" | "favorite";

export type QueryItems = { kind: "tracks"; items: TrackDto[] } | { kind: "albums"; items: AlbumDto[] } | { kind: "artists"; items: ArtistDto[] } | { kind: "folders"; items: FolderDto[] } | { kind: "genres"; items: GenreDto[] };

export type QueryOperator = "eq" | "neq" | "contains" | "startsWith" | "gt" | "gte" | "lt" | "lte" | "in";

export type QueryPage = {
	entity: EntityKind,
	page: number,
	pageSize: number,
	hasMore: boolean,
	items: QueryItems,
};

export type QueryRequest = {
	entity: EntityKind,
	query: Expr,
	sort: QuerySort[],
	page: number,
	pageSize: number,
};

export type QuerySort = {
	field: QueryField,
	direction: SortDirection,
};

export type QueryValue = string | number | null | boolean | string[] | (number | null)[];

export type QueueInsertMode = "replace" | "next" | "append";

export type RepeatMode = "off" | "track" | "queue";

export type ResolvedPlaylist = {
	playlist: Playlist,
	items: ResolvedPlaylistItem[],
};

export type ResolvedPlaylistItem = {
	item: StaticPlaylistItem,
	track: TrackDto | null,
	suggested_path: string | null,
};

export type ResolvedTheme = {
	id: string,
	name: string,
	appearance: ThemeAppearance,
	tokens: { [key in string]: ThemeTokenValue },
	warnings: string[],
};

export type ScanProgress = {
	discovered: number,
	indexed: number,
	skippedUnchanged: number,
	failed: number,
	currentPath: string | null,
	currentTitle: string | null,
	complete: boolean,
};

export type SearchRequest = {
	input: string,
	limitPerSection: number,
};

export type SortDirection = "asc" | "desc";

export type StaticPlaylistItem = {
	path: string,
	hint: TrackHint,
};

export type ThemeAppearance = "light" | "dark";

export type ThemeCatalog = {
	themes: ThemeSummary[],
	warnings: string[],
};

export type ThemeSelectionDto = {
	lightSelection: string,
	darkSelection: string,
	followSystemAppearance: boolean,
};

export type ThemeSummary = {
	id: string,
	name: string,
	appearance: ThemeAppearance,
	basedOn: string | null,
	builtIn: boolean,
};

export type ThemeTokenDescriptor = {
	id: string,
	label: string,
	category: string,
	kind: ThemeTokenKind,
	minimum: number | null,
	maximum: number | null,
	defaultValue: ThemeTokenValue,
};

export type ThemeTokenKind = "color" | "number" | "text" | "boolean";

export type ThemeTokenValue = string | number | null | boolean;

export type TrackDto = {
	id: string,
	relPath: string,
	title: string | null,
	artist: string | null,
	artists: string[],
	albumArtist: string | null,
	album: string | null,
	year: number | null,
	trackNo: number | null,
	discNo: number | null,
	genres: string[],
	composer: string | null,
	durationMs: number | null,
	codec: string | null,
	container: string | null,
	sampleRate: number | null,
	bitDepth: number | null,
	channels: number | null,
	bitrate: number | null,
	artworkKey: string | null,
	addedAt: number | null,
	lastPlayed: number | null,
	playCount: number,
	favorite: boolean,
};

export type TrackHint = {
	title: string | null,
	artist: string | null,
	album: string | null,
	duration_ms: number | null,
	disc_no: number | null,
	track_no: number | null,
};

export type ViewDefinition = {
	schema_version: number,
	id: string,
	name: string,
	icon: string | null,
	entity: EntityKind,
	query: Expr,
	group_by: QueryField[],
	sort: QuerySort[],
	layout: ViewLayout,
	pin_to_sidebar: boolean,
};

export type ViewDensity = "compact" | "comfortable" | "spacious";

export type ViewLayout = {
	kind: LayoutKind,
	density: ViewDensity,
	cover_size: number | null,
	visible_fields: QueryField[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

