// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appHealth: () => __TAURI_INVOKE<AppHealth>("app_health"),
	libraryChooseRoot: () => typedError<{
	libraryId: string,
	rootInstanceHash: string,
	rootPath: string,
	trackCount: number,
	status: LibraryStatus,
} | null, string>(__TAURI_INVOKE("library_choose_root")),
	libraryStatus: () => typedError<{
	libraryId: string,
	rootInstanceHash: string,
	rootPath: string,
	trackCount: number,
	status: LibraryStatus,
} | null, string>(__TAURI_INVOKE("library_status")),
};

/** Events */
export const events = {
	libraryScanProgress: makeEvent<LibraryScanEvent>("library://scan-progress"),
};

/* Types */
export type AppHealth = {
	appName: string,
	version: string,
	status: string,
};

export type LibraryScanEvent = {
	summary: LibrarySummary,
	progress: ScanProgress,
	error: string | null,
};

export type LibraryStatus = "ready" | "scanning" | "failed";

export type LibrarySummary = {
	libraryId: string,
	rootInstanceHash: string,
	rootPath: string,
	trackCount: number,
	status: LibraryStatus,
};

export type ScanProgress = {
	discovered: number,
	indexed: number,
	skippedUnchanged: number,
	failed: number,
	currentPath: string | null,
	currentTitle: string | null,
	complete: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

